[window]

dimensions.columns = 105
dimensions.lines = 28

opacity = 0.75

padding.x = 0
padding.y = 0

decorations = "None"
decorations_theme_variant = "Dark"

[font]

normal.family = "FiraCode Nerd Font Mono Med"

size = 8.5

[terminal]
shell = "fish"

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[colors]
[colors.primary]
background = "#1d2021"

[colors.normal]
red = "#d65d0e"
[colors.bright]
red = "#fe8019"
